---
title: "About me"
output: 
  html_document:
    toc: true
    toc_float: true
---

### Education Experience

[09/2024 – 05/2026]{style="float:left;"}\
**Columbia University Mailman School of Public Health**, the United States MPH in Biostatistics｜First Year GPA: 4.00.\

[09/2020 – 06/2024]{style="float:left;"}\
**Xi'an Jiaotong-Liverpool University (XJTLU)**, China BSc in Financial Mathematics \| Major GPA: 3.83/4.0 \| Upper Second Class Degree with honours.

### Research Experience
 * **Staten Island Hunger Task Force** | Columbia University | Prof. Heather Butts

 * **Bayesian Dynamic Recommendation System for Dose-Finding** | Xi’an Jiaotong Liverpool University | Advisor: Professor Xiaojun Zhu.         
 * **Final Year Project: Phase I Clinical Trial Design** | Xi’an Jiaotong Liverpool University | Advisor: Professor Xiaojun Zhu.

### Work Experience
 * **SAS Statistical Procedure Development** | Peking University Institute for Advanced Information Technology.
 * **Statistical Assistant Intern** | First Affiliated Hospital of Zhengzhou University

### Activities
 * Finished **half-marathon** (about **22km**) within 2 h 24 min 51s.
 * Completed The Journey of Xuanzang, a **112km** trek through the Gobi desert.
 * Completed a **240 km**, two-day-and-one-night cycling trip around Shaolin Temple.
